# Generated by Django 3.2 on 2021-05-13 06:01

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_num', models.CharField(blank=True, max_length=255, verbose_name='订单编号')),
                ('settlement_order_num', models.CharField(blank=True, max_length=255, verbose_name='结算订单编号')),
                ('invoice_num', models.CharField(blank=True, max_length=255, verbose_name='发票号码')),
                ('invoice_top_num', models.CharField(blank=True, max_length=255, verbose_name='发票抬头')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='实际金额')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='服务开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='服务结束时间')),
                ('order_pic', models.ImageField(blank=True, storage=django_minio_backend.models.MinioBackend(bucket_name='image'), upload_to='order/%Y/%m/%d', verbose_name='订单付款截图')),
                ('order_contract', models.FileField(blank=True, storage=django_minio_backend.models.MinioBackend(bucket_name='doc'), upload_to='order/%Y/%m/%d', verbose_name='订单合同扫描件')),
                ('attach', models.TextField(blank=True, max_length=255, verbose_name='附加赠品')),
                ('effect', models.BooleanField(default=True, verbose_name='是否保证效果')),
                ('whether_to_cooperate', models.BooleanField(default=True, verbose_name='是否合作转接')),
                ('des_effect', models.TextField(blank=True, verbose_name='效果说明')),
                ('effect_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='保证金额')),
                ('transaction_type', models.IntegerField(blank=True, choices=[(1, '新签'), (2, '续签'), (3, '增值')], null=True, verbose_name='交易类型')),
                ('commission', models.BooleanField(default=False, verbose_name='是否有提成')),
                ('commission_start', models.IntegerField(blank=True, choices=[(1, '1%'), (2, '2%'), (3, '2.5%'), (4, '3%'), (5, '3.5%'), (6, '4%'), (7, '4.5%'), (8, '5%'), (9, '5.5%'), (10, '6%'), (11, '7%'), (12, '8%'), (13, '9%'), (14, '10%')], null=True, verbose_name='提点比例开始')),
                ('commission_end', models.IntegerField(blank=True, choices=[(1, '1%'), (2, '2%'), (3, '2.5%'), (4, '3%'), (5, '3.5%'), (6, '4%'), (7, '4.5%'), (8, '5%'), (9, '5.5%'), (10, '6%'), (11, '7%'), (12, '8%'), (13, '9%'), (14, '10%')], null=True, verbose_name='提点比例结束')),
                ('mention', models.TextField(blank=True, verbose_name='提点说明')),
                ('is_help', models.BooleanField(default=False, verbose_name='是否帮谈')),
                ('help_level', models.IntegerField(blank=True, choices=[(1, '2%'), (2, '10%'), (3, '30%'), (4, '50%')], null=True, verbose_name='帮谈提点')),
                ('cooperation_cycle', models.IntegerField(blank=True, choices=[(1, '单月'), (2, '三个月'), (3, '季度'), (4, '半年'), (5, '年度')], null=True, verbose_name='合作周期')),
                ('customer', models.ManyToManyField(related_name='order', to='customers.CustomerModel', verbose_name='关联联系人')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'db_table': 'crm_order',
            },
        ),
    ]
