# Generated by Django 3.2 on 2021-04-29 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='类目名称')),
            ],
            options={
                'verbose_name': '店铺类目表',
                'verbose_name_plural': '店铺类目表',
                'db_table': 'crm_shop_store_category',
            },
        ),
        migrations.CreateModel(
            name='MainFollowupMethodsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='主要跟进方式')),
            ],
            options={
                'verbose_name': '主要跟进方式',
                'verbose_name_plural': '主要跟进方式',
                'db_table': 'crm_shop_main_followup_method',
            },
        ),
        migrations.CreateModel(
            name='OpeningTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='开店时长')),
            ],
            options={
                'verbose_name': '开店时长',
                'verbose_name_plural': '开店时长',
                'db_table': 'crm_shop_opening_time',
            },
        ),
        migrations.CreateModel(
            name='PlatformModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='客户平台')),
            ],
            options={
                'verbose_name': '客户平台',
                'verbose_name_plural': '客户平台',
                'db_table': 'crm_shop_platform',
            },
        ),
        migrations.CreateModel(
            name='ShopNatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='店铺性质')),
            ],
            options={
                'verbose_name': '店铺性质',
                'verbose_name_plural': '店铺性质',
                'db_table': 'crm_shop_shop_nature',
            },
        ),
        migrations.CreateModel(
            name='SupplySituationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='货源情况')),
            ],
            options={
                'verbose_name': '货源情况',
                'verbose_name_plural': '货源情况',
                'db_table': 'crm_shop_supply_situation',
            },
        ),
        migrations.CreateModel(
            name='TransactionCycleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='成交周期')),
            ],
            options={
                'verbose_name': '成交周期',
                'verbose_name_plural': '成交周期',
                'db_table': 'crm_shop_transaction_cycle',
            },
        ),
        migrations.CreateModel(
            name='StoreTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='店铺类型')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StoreType', to='shops.platformmodel', verbose_name='客户平台')),
            ],
            options={
                'verbose_name': '店铺类型',
                'verbose_name_plural': '店铺类型',
                'db_table': 'crm_shop_store_type',
            },
        ),
        migrations.CreateModel(
            name='StoreLevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='店铺层级')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StoreLevel', to='shops.platformmodel', verbose_name='客户平台')),
            ],
            options={
                'verbose_name': '店铺层级',
                'verbose_name_plural': '店铺层级',
                'db_table': 'crm_shop_store_level',
            },
        ),
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deletedAt', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('shop_name', models.CharField(max_length=255, unique=True, verbose_name='店铺名')),
                ('url', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='店铺链接')),
                ('credit_rating', models.CharField(blank=True, max_length=255, null=True, verbose_name='信用等级')),
                ('product_quantity', models.IntegerField(blank=True, null=True, verbose_name='产品数量')),
                ('cumulative_sales', models.IntegerField(blank=True, null=True, verbose_name='累计销售量')),
                ('sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='销售额')),
                ('shop_opening_time', models.DateField(blank=True, null=True, verbose_name='开店时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shops.categorymodel', verbose_name='店铺类目')),
            ],
            options={
                'verbose_name': '客户店铺信息表',
                'verbose_name_plural': '客户店铺信息表',
                'db_table': 'crm_shop',
            },
        ),
    ]
