# Generated by Django 3.2 on 2021-04-29 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='create_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='main_followup_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shops.mainfollowupmethodsmodel', verbose_name='主要跟进方式'),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='opening_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shops.openingtimemodel', verbose_name='开店周期'),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shops.platformmodel', verbose_name='店铺平台'),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='shop_nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shops.shopnaturemodel', verbose_name='店铺性质'),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='store_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shops.storelevelmodel', verbose_name='店铺层级'),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='store_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shops.storetypemodel', verbose_name='店铺类型'),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='supply_situation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shops.supplysituationmodel', verbose_name='货源情况'),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='transaction_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shops.transactioncyclemodel', verbose_name='成交周期'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='shops.categorymodel', verbose_name='上级类别'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shops.platformmodel', verbose_name='客户平台'),
        ),
    ]
