# Generated by Django 3.2 on 2021-04-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopmodel',
            old_name='shop_name',
            new_name='name',
        ),
    ]
