# Generated by Django 3.2 on 2021-05-06 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followups', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupmodel',
            name='follow_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to=settings.AUTH_USER_MODEL, verbose_name='跟进人'),
        ),
        migrations.AddField(
            model_name='followupmodel',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='shops.shopmodel', verbose_name='关联店铺'),
        ),
    ]
