# Generated by Django 3.2 on 2021-04-29 07:23

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import libs.Id_card_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_num', models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='手机号码')),
                ('real_name', models.CharField(max_length=255, verbose_name='真实姓名')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, validators=[libs.Id_card_validator.id_validator], verbose_name='身份证号码')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生年月日')),
                ('password', models.CharField(blank=True, default='123456', max_length=255, verbose_name='登录密码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('gender', models.IntegerField(choices=[(0, '未设置'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('status', models.IntegerField(choices=[(1, '考核期'), (2, '试用'), (3, '转正'), (4, '休假'), (5, '离职')], default=1, verbose_name='用户状态')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否管理员')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='上次登录时间')),
                ('lottery_times', models.IntegerField(blank=True, default=10, null=True, verbose_name='抽奖次数')),
                ('avatar', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='upload.avatarmodel', verbose_name='头像')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '员工表',
                'verbose_name_plural': '员工表',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_num', 'username'], name='p_u_idx'),
        ),
    ]
