# Generated by Django 3.2 on 2021-05-13 06:01

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.ImageField(blank=True, storage=django_minio_backend.models.MinioBackend(bucket_name='image'), upload_to='avatar/%Y/%m/%d', verbose_name='跟进聊天截图')),
            ],
            options={
                'verbose_name': '用户头像',
                'verbose_name_plural': '用户头像',
                'db_table': 'upload_avatar',
            },
        ),
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.ImageField(blank=True, storage=django_minio_backend.models.MinioBackend(bucket_name='doc'), upload_to='followup/%Y/%m/%d', verbose_name='跟进聊天文档')),
            ],
            options={
                'verbose_name': '跟进聊天文档',
                'verbose_name_plural': '跟进聊天文档',
                'db_table': 'upload_followup_document',
            },
        ),
        migrations.CreateModel(
            name='RecordingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.ImageField(blank=True, storage=django_minio_backend.models.MinioBackend(bucket_name='audio'), upload_to='followup/%Y/%m/%d', verbose_name='跟进聊天录音')),
            ],
            options={
                'verbose_name': '跟进聊天录音',
                'verbose_name_plural': '跟进聊天录音',
                'db_table': 'upload_followup_recording',
            },
        ),
        migrations.CreateModel(
            name='ScreenshotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.ImageField(blank=True, storage=django_minio_backend.models.MinioBackend(bucket_name='image'), upload_to='followup/%Y/%m/%d', verbose_name='跟进聊天截图')),
            ],
            options={
                'verbose_name': '跟进聊天截图',
                'verbose_name_plural': '跟进聊天截图',
                'db_table': 'upload_followup_screenshot',
            },
        ),
    ]
