# Generated by Django 3.2 on 2021-04-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.SmallIntegerField(choices=[(0, '待审核'), (2, '通过'), (3, '未通过')], default=0, verbose_name='审批状态')),
                ('reason', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='原因')),
            ],
            options={
                'verbose_name': '新增跟进审批表',
                'verbose_name_plural': '新增跟进审批表',
                'db_table': 'crm_followup_review',
            },
        ),
        migrations.CreateModel(
            name='OrderReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.SmallIntegerField(choices=[(0, '待审核'), (2, '通过'), (3, '未通过')], default=0, verbose_name='审批状态')),
                ('reason', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='原因')),
            ],
            options={
                'verbose_name': '订单审批表',
                'verbose_name_plural': '订单审批表',
                'db_table': 'crm_order_review',
            },
        ),
        migrations.CreateModel(
            name='ShopReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.SmallIntegerField(choices=[(0, '待审核'), (2, '通过'), (3, '未通过')], default=0, verbose_name='审批状态')),
                ('reason', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='原因')),
            ],
            options={
                'verbose_name': '新增店铺审批表',
                'verbose_name_plural': '新增店铺审批表',
                'db_table': 'crm_shop_review',
            },
        ),
    ]
